name: flightgear
base: core18 
version: '2020.3.2'
summary: FlightGear
description: |
  FlightGear

grade: stable
confinement: strict

apps:                    
  flightgear:       
    command: desktop-launch $SNAP/bin/fgfs --fg-root=$SNAP_USER_COMMON/fgdata
    plugs: [network, network-bind, unity7, opengl, home, audio-playback, removable-media, joystick]
    desktop: share/applications/org.flightgear.FlightGear.desktop
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"

parts:
  simgear:
    source: https://github.com/FlightGear/simgear
    source-type: git
    source-tag: "version/2020.3.2"
    plugin: cmake
  # flightgear-data:
  #   source: https://sourceforge.net/projects/flightgear/files/release-2019.1/FlightGear-2019.1.2-data-rc.tar.bz2
  #   plugin: dump
  #   organize:
  #     '*': fgdata/
  flightgear:
    after: [simgear]
    source: https://github.com/FlightGear/flightgear
    source-type: git
    source-tag: "version/2020.3.2"
    plugin: cmake
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=flightgear|Icon=${SNAP}/share/icons/hicolor/128x128/apps/flightgear.png|' $SNAPCRAFT_PART_INSTALL/share/applications/org.flightgear.FlightGear.desktop
    build-packages:
      - qt5-default
      - qtbase5-dev
      - qtbase5-private-dev
      - qtdeclarative5-dev
      - qtdeclarative5-private-dev
      - qtscript5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qttools5-private-dev
      - qtxmlpatterns5-dev-tools
      - libboost-dev
      - libopenscenegraph-3.4-dev
      - libqt5svg5-dev
      - libplib-dev
      - libopenal-dev
      - libcurl4-openssl-dev
    stage-packages:
      - libasn1-8-heimdal
      - libasound2
      - libcurl4
      - libdouble-conversion1
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgssapi3-heimdal
      - libharfbuzz0b
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libicu60
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libopenal1
      - libopenscenegraph-3.4-131
      - libopenthreads20
      - libplib1
      - libpng16-16
      - libpsl5
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5qml5
      - libqt5quick5
      - libqt5widgets5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libsndio6.1
      - libwind0-heimdal
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libglu1-mesa
      - libslang2
      - libgtk2.0-0 
      - pulseaudio
      - libblas3 
      - liblapack3
      - yad
      - libgtk-3-0
      - libnotify4
      - qml-module-qtquick2
      - qml-module-qtquick-window2
  desktop-qt5:
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    make-parameters:
     - FLAVOR=qt5
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - try:
        - appmenu-qt5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
